package baymax;

import baymax.data.TaskData;
import baymax.ui.Ui;
import baymax.ui.UiBuffer;

/**
 * Represents the main logic and entry point for the Baymax application.
 * Acts as the core bridge connecting the user interface, parser, and data storage.
 */
public class Baymax {
    
    /**
     * Constructs a Baymax instance.
     * Initializes the application by loading saved tasks from the hard disk into memory.
     */
    public Baymax() {
        TaskData.loadTasks();
    }
    
    /**
     * Runs the main entry function for the Baymax Command Line Interface (CLI).
     *
     * @param args Command line arguments.
     */
    public static void main(String[] args){
        Ui.readInput();
    }
    
    /**
     * Generates a response from the Baymax logic given a user input string.
     * This is utilized by the Graphical User Interface (GUI) to fetch chatbot replies.
     *
     * @param input The command entered by the user.
     * @return The text response generated by Baymax's execution logic.
     */
    public String getResponse(String input) {
        // ASSERTION (Precondition): The GUI should never pass a null string to the logic brain
        assert input != null : "Input passed to Baymax logic cannot be null";
        
        Ui.handleGuiInput(input);
        String response = UiBuffer.getAndClear();
        
        // ASSERTION (Postcondition): Baymax must always return a valid string back to the GUI
        assert response != null : "Response generated by Baymax logic cannot be null";
        
        return response;
    }
}