package baymax.ui;

import baymax.Baymax;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
/**
 * Controller for the main GUI.
 */
public class MainWindow extends AnchorPane {
    @FXML
    private ScrollPane scrollPane;
    @FXML
    private VBox dialogContainer;
    @FXML
    private TextField userInput;
    @FXML
    private Button sendButton;
    
    private Baymax baymax;
    
    private Image userImage = new Image(this.getClass().getResourceAsStream("/images/UserImage.png"));
    private Image baymaxImage = new Image(this.getClass().getResourceAsStream("/images/BaymaxImage.png"));
    
    @FXML
    public void initialize() {
        scrollPane.vvalueProperty().bind(dialogContainer.heightProperty());
    }
    
    /** Injects the Baymax instance */
    public void setBaymax(Baymax d) {
        baymax = d;
        
        Ui.printOpeningMessage();
        dialogContainer.getChildren().add(DialogBox.getBaymaxDialog(UiBuffer.getAndClear(), baymaxImage)
        );
    }
    
    /**
     * Creates two dialog boxes, one echoing user input and the other containing Baymax's reply and then appends them to
     * the dialog container. Clears the user input after processing.
     */
    @FXML
    private void handleUserInput() {
        String input = userInput.getText();
        String response = baymax.getResponse(input);
        dialogContainer.getChildren().addAll(
                DialogBox.getUserDialog(input, userImage),
                DialogBox.getBaymaxDialog(response, baymaxImage)
        );
        userInput.clear();
        
        // ------------------ NEW EXIT LOGIC ------------------
        // Code below generated by AI
        if (input.trim().equalsIgnoreCase("bye")) {
            // Wait 1.5 seconds so the user can read the goodbye message
            javafx.animation.PauseTransition delay = new javafx.animation.PauseTransition(javafx.util.Duration.seconds(2.0));
            delay.setOnFinished(event -> javafx.application.Platform.exit());
            delay.play();
        }
    }
}
